"""Agrega campo fecha_creacion

Revision ID: 5af1f65583e5
Revises: 
Create Date: 2025-07-04 08:33:09.114800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af1f65583e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuariospowerbi')
    with op.batch_alter_table('Mantenimientos_pc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Mantenimientos_pc', schema=None) as batch_op:
        batch_op.drop_column('fecha_registro')

    op.create_table('usuariospowerbi',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__usuarios__3213E83FC54F7E3C')
    )
    # ### end Alembic commands ###
